export { HomePage } from './HomePage'
export { ServicePage } from './ServicePage'
export { ProductsPage, ProductDetailPage } from './ProductPages'
export { AboutPage, ContactPage, NotFoundPage } from './InfoPages'
export { ArticlePage } from './KnowledgePages'
export { CatalogCategoryPage } from './CatalogCategoryPage'
